### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by ghost** [lalor/python_for_linux_system_administration#1]
### 第50页

2中的`ConfigParser`模块，在3中已经改为规范的小写`configparse`，标注一下是2还是3比较好。

```
get、getboolean、getinit、getfloat：获取选项的值。
```

这一段，getinit写错，应该是getint。

### 第51页
```
In [13]: cf.set('mysql', 'port', 3306)
```
2中是生效的，3中已经改为传入值的必须是字符串: `cf.set('mysql', 'port', '3306')`。标注一下是2和3的区别比较好。

**Comment by lalor** [comment]
很仔细的勘误，非常感谢，会在再版时全部修复。

再次感谢你帮忙改进书籍质量。

**Comment by lalor** [comment]
已经增加到勘误列表中。
