### ISSUE TITLE
书中filename = sys.argv[1]

### ISSUE THREAD

**Issue by tmaccs** [lalor/python_for_linux_system_administration#3]
文件名应该是第一个参数，即应该是sys.argv[0],
书中所有(目前看到第五章)获取filename的代码中，
都写的是filename = sys.argv[1]，
我认为应该修改为filename = sys.argv[0].

**Comment by lalor** [comment]
额，问题的上下文可以再补充一下吗，哪一章哪一节的例子？把代码截图贴一下？

**Comment by tmaccs** [comment]
<img width="1014" alt="2018-09-26 11 50 12" src="https://user-images.githubusercontent.com/10339482/46092344-45f39e80-c1e7-11e8-8054-d0af649a19f4.png">

这里的line#9, sys.argv[1]获得的应该是第二个参数, 
应该修改为filename = sys.argv[0]才能获得文件名，然后打印出文件里面的代码。

除此之外, 书中其他所有的获取filename都是用的sys.argv[1]，我认为应该修改为sys.argv[0]。

**Comment by lalor** [comment]
例如，这段代码的文件名是"test_file_access.py"，这里就是要去获取第二个参数，使用方式如“python
test_file_access.py your_file”。

按照你的思路的话，程序就只能判断当前执行的这个文件有没有可执行权限了，一方面逻辑上不合理，另一方面也不通用。如果我要判断另外一个文件"a.sh"是否具有可执行权限呢？

IAN.Y <notifications@github.com> 于2018年9月27日周四 上午12:13写道：

**Comment by tmaccs** [comment]
确实是我思路太局限了，谢谢解答！
