### ISSUE TITLE
check_is_admin_with_decorator.py 

### ISSUE THREAD

**Issue by jiazhan** [lalor/python_for_linux_system_administration#4]
Hi MingXing:
I got error running original code with class initialization as below under python 2.7.5, 
can you help to verify it ?

ps=Stack()
ps.put('admin','first')
print ps.get('admin')

**Comment by lalor** [comment]
具体错误是什么，贴一下截图？

**Comment by jiazhan** [comment]
您好，
感谢您的回复！
详见下面，请查看
我加了初始化类的语句，之前
用
ps.put('first','admin')
引用方法，也会有报错，后来改用

ps.put('first',username='admin')
报错如下，


~~~~~~~~~~~~~~~~~~~~~~

def check_is_admin(f):
    def wrapper(*args, **kwargs):
        print "kwargs is",kwargs
        if kwargs.get('username') != 'admin':
        #if  'admin' not in args:
            raise Exception("This user is not allowed to put/get elem")
        return f(*args, **kwargs)
    return wrapper


class Stack:
    def __init__(self):
        self.storage = []

    @check_is_admin
    def put(self, username, elem):
        self.storage.append(elem)

    @check_is_admin
    def get(self, username):
        if not self.storage:
            raise Exception("There is no elem in stack")
        return self.storage.pop()

ps=Stack()
ps.put('first',username='admin')
print ps.get('admin')

[root@host section1]# python mycheck_admin.py
kwargs is {'username': 'admin'}
Traceback (most recent call last):
  File "mycheck_admin.py", line 26, in <module>
    ps.put('first',username='admin')
  File "mycheck_admin.py", line 7, in wrapper
    return f(*args, **kwargs)
TypeError: put() got multiple values for keyword argument 'username'
[root@host section1]#






在 2018-09-26 09:53:20，"lalor" <notifications@github.com> 写道：


具体错误是什么，贴一下截图？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lalor** [comment]
ps.put('first',username='admin')

'first'会传给put函数的第一个参数，即username，然后你又通过关键字参数传递了一个username，所以重复了。

你可以ps.put(elem='first', username='admin')或者ps.put('admin', 'first')

这个是Python中，函数传递参数相关的知识哈。

**Comment by jiazhan** [comment]
您好，
感谢您的提示，我需要补补基础课：）
按您的提示，测试使用
ps.put(elem='first', username='admin')
成功了，
但 使用
ps.put('admin','first')
会报错，如下，
[root@host section1]# python  check_is_admin_with_decorator.py
Traceback (most recent call last):
  File "check_is_admin_with_decorator.py", line 23, in <module>
    ps.put('admin','first')
  File "check_is_admin_with_decorator.py", line 4, in wrapper
    raise Exception("This user is not allowed to put/get elem")
Exception: This user is not allowed to put/get elem


我想是由于 wrapper 函数中使用
kwargs.get('username') != 'admin':
这个检查只使用字典做参数检查，所以使用关键字参数作为实参传递给wrapper，是吗？






在 2018-09-27 09:46:28，"lalor" <notifications@github.com> 写道：


ps.put('first',username='admin')

'first'会传给put函数的第一个参数，即username，然后你又通过关键字参数传递了一个username，所以重复了。

你可以ps.put(elem='first', username='admin')或者ps.put('admin', 'first')

这个是Python中，函数传递参数相关的知识哈。

**Comment by lalor** [comment]
我想是由于 wrapper 函数中使用
kwargs.get('username') != 'admin':
这个检查只使用字典做参数检查，所以使用关键字参数作为实参传递给wrapper，是吗？

-- 理解非常到位

jiazhan <notifications@github.com> 于2018年9月27日周四 上午11:32写道：
