### ISSUE TITLE
根目录下README.md存在明显错别字

### ISSUE THREAD

**Issue by DingGuodong** [lalor/python_for_linux_system_administration#7]
应该是“公众号”，原文是“公总号”。

**错误：**
>在InsideMySQL公总号发布的国产数据库排行榜中，MySQL偶尔能够超过Oracle数据库，成为国内最热的数据库。

**正确：**
>在InsideMySQL公众号发布的国产数据库排行榜中，MySQL偶尔能够超过Oracle数据库，成为国内最热的数据库。

**Comment by lalor** [comment]
感谢提醒。
